@startuml

class Museum {
    - code: String
    - name: String
    - address: String
    + getExhibits(): List<Exhibit>
    + getStaffMembers(): List<Staff>
}

class Exhibit {
    - id: String
    - museumCode: String
    - artist_id: String
    - title: String
    - description: String
    - date: Date
    + getInfo(): String
}

class Staff {
    - name: String
    - museumCode: String
    - role: String
    + getRole(): String
}

class Artist {
    - id: String
    - name: String
    - biography: String
    + getArtworks(): List<ArtWork>
}

class ArtWork {
    - name: String
    - year: String
    - artist_id: String
    - exhibit_id: String
}
class Visitor {
    - name: String
    - visitDate: Date
    + visit(exhibit: Exhibit)
}

Museum "1" -> "0..*" Exhibit : Contains
Museum "1" -> "0..*" Staff : Employs
Exhibit "0..*" <-> "*..*" Artist : Created by
Visitor "1" -- "0..*" Exhibit : Visits

@enduml
